Repository rakenduste-programmeerimine-2021/investofox, pull requests merged in 2021-11, with the labels that each got.

#15 Docker - FE, BE, DB connections made + readme update + routes
  LICENSE
  README.md
  backend-node/.gitignore
  backend-node/Dockerfile
  backend-node/package-lock.json
  backend-node/package.json
  backend-node/src/server.js
  frontend/.env
  frontend/.gitignore
  frontend/Dockerfile
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/pages/Register.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  installation
  local-dev/docker-compose.yml
Labels: BE

#32 Install MUI lib + added some deps to docker
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
  installation
Labels: BE, FE

#37 Register page FE - form and design
  frontend/src/InvestoFoxLogo.svg
  frontend/src/components/RegisterForm.css
  frontend/src/components/RegisterForm.js
  frontend/src/fonts/Antic-Regular.ttf
  frontend/src/index.css
  frontend/src/pages/Register.css
  frontend/src/pages/Register.js
Labels: FE

#40 Backend endpoints, user schemas, repos, controllers, routes
  README.md
  backend-node/.env
  backend-node/package-lock.json
  backend-node/package.json
  backend-node/src/controllers/authController.js
  backend-node/src/middleware/jwtAuth.js
  backend-node/src/middleware/validationMiddleware.js
  backend-node/src/models/User.js
  backend-node/src/routes/auth.js
  backend-node/src/server.js
  frontend/src/App.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
Labels: BE

#44 Register page class name fixes + link to home page
  frontend/src/components/RegisterForm.css
  frontend/src/components/RegisterForm.js
  frontend/src/pages/Register.css
  frontend/src/pages/Register.js
Labels: FE

#45 Register form save user to db
  backend-node/src/controllers/authController.js
  backend-node/src/routes/auth.js
  backend-node/src/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LoginForm.js
  frontend/src/components/RegisterForm.js
Labels: BE

#51 Login save data to db
  frontend/Dockerfile
  frontend/src/App.css
  frontend/src/components/LoginForm.js
  frontend/src/components/RegisterForm.js
Labels: FE
