Repository rakenduste-programmeerimine-2021/investofox, pull requests merged in 2021-12, with the labels that each got.

#65 Add order to user
  backend-node/package-lock.json
  backend-node/package.json
  backend-node/src/controllers/authController.js
  backend-node/src/controllers/orderController.js
  backend-node/src/middleware/jwtAuth.js
  backend-node/src/models/User.js
  backend-node/src/routes/auth.js
  backend-node/src/server.js
  frontend/src/App.js
  frontend/src/components/LoginForm.js
  frontend/src/components/OrderForm.js
  frontend/src/components/PortfolioForm.js
  frontend/src/index.js
  frontend/src/pages/Order.js
  frontend/src/store/actions.js
  frontend/src/store/index.js
Labels: BE, FE

#64 Navigation bar
  frontend/src/App.js
  frontend/src/IFicon.png
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.js
Labels: FE

#67 NavBar design fix
  frontend/src/components/LoginForm.css
  frontend/src/components/NavBar.css
  frontend/src/pages/Portfolio.css
  frontend/src/pages/Portfolio.js
Labels: FE

#68 Show stock order list
  backend-node/src/controllers/authController.js
  backend-node/src/routes/auth.js
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Columns.js
  frontend/src/components/LoginForm.js
  frontend/src/components/NavBar.js
  frontend/src/components/OrderForm.js
  frontend/src/components/PortfolioForm.js
  frontend/src/pages/Order.js
  frontend/src/pages/OrderList.js
  frontend/src/pages/OrderListv1.js
  frontend/src/pages/Portfolio.js
Labels: BE, FE

#69 LoginForm password toggler
  frontend/src/components/LoginForm.css
  frontend/src/components/LoginForm.js
Labels: FE

#71 RegisterForm password toggler
  frontend/src/components/RegisterForm.css
  frontend/src/components/RegisterForm.js
Labels: FE

#73 LoginForm password toggler fix
  frontend/src/components/LoginForm.js
Labels: FE

#79 Stock API page design change
  frontend/src/components/PortfolioForm.css
  frontend/src/components/PortfolioForm.js
  frontend/src/pages/Api.css
  frontend/src/pages/Api.js
Labels: FE

#80 Add order page design change
  frontend/src/components/OrderForm.css
  frontend/src/components/OrderForm.js
  frontend/src/pages/Order.css
  frontend/src/pages/Order.js
Labels: FE

#85 Real time current price calc closes #84 #35 #39
  backend-node/package-lock.json
  backend-node/src/controllers/authController.js
  backend-node/src/routes/auth.js
  frontend/package-lock.json
  frontend/src/components/Chart.js
  frontend/src/components/LoginForm.js
  frontend/src/components/OrderForm.js
  frontend/src/components/PortfolioForm.js
  frontend/src/components/RegisterForm.js
  frontend/src/components/StockFetcher.js
  frontend/src/components/Utils/StockApi.js
  frontend/src/pages/OrderList.js
  frontend/src/pages/OrderListv1.js
  installation
Labels: FE

#88 Delete function for orderList
  backend-node/src/controllers/authController.js
  backend-node/src/routes/auth.js
  frontend/src/components/Chart.js
  frontend/src/components/NavBar.js
  frontend/src/components/OrderForm.js
  frontend/src/components/PortfolioForm.js
  frontend/src/components/StockFetcher.js
  frontend/src/pages/OrderList.js
Labels: BE, FE

#90 Update README.md
  README.md
Labels: documentation

#92 stock fetch chart
  backend-node/src/test/test.js
  frontend/src/components/PortfolioForm.js
Labels: FE
